# __version__.py
# autogenerated by keats 0.2.28
__version__ = "0.1.6"
__name__ = "terrarium-capp"
__title__ = "terrarium-capp"
__authors__ = ["Justin Vrana <justin.vrana@gmail.com>"]
__repo__ = None
__homepage__ = "https://www.github.com/jvrana/Terrarium"
__description__ = "Adaptive Computer Aided Process Planner"
