PRIMARY_KEY = "primary_key"
MODEL_CLASS = "__class__"

INTERNAL_EDGE = "external"
EXTERNAL_EDGE = "internal"
SAMPLE_TO_SAMPLE = "sample_to_sample"

WEIGHT = "weight"
EDGE_TYPE = "edge_type"

# OPERATION_TYPE = "operation_type"
# IO_TYPE_FILTER = "allowable_field_type"
# IO_TYPE = "field_type"
# OPERATIONS = "operations"
# IOS = "field_values"
# PART = "part"
# EXTERNAL_EDGE = "external"
# INTERNAL_EDGE = "internal"
# COLLECTIONS = "collections"
# OBJECT_TYPE = "object_type"
# OBJECT_TYPE_ID = "object_type_id"
# SAMPLE_TYPE_ID = "sample_type_id"
# SAMPLE_ID = "sample_id"
# SAMPLE = "sample"
